name: 'Flake8 Style Evaluator'
description: 'Runs Flake8 over a project and comment on the student PR the errors found.'
inputs:
  token:
    description: 'The GitHub token to use for making API requests.'
    required: true
  pr_number:
    description: 'Pull Request number that trigger build.'
    required: true

runs:
  using: 'composite'
  steps:
    - id: run_flake8
      shell: bash
      run: ${{ github.action_path }}/lint.sh
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        INPUT_PR_NUMBER: ${{ inputs.pr_number }}
        EVALUATOR_REQUIREMENTS: ${{ github.action_path }}/requirements.txt
        EVALUATOR_SRC: ${{ github.action_path }}/src
